# .ps_project/config.yaml:

version: 1

project: "dive-into-dl"
# experiment: "experiment-name" #[optional, default:<repo name>]
type: "single" #[single|multi-grpc|multi-mpi]
#ports: "5000" #[optional, default:5000]
